# Generated by Django 5.1.2 on 2025-03-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ValidationLogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("endpoint", models.CharField(max_length=255)),
                ("domain", models.CharField(max_length=255)),
                ("url", models.CharField(max_length=32768)),
                ("success", models.BooleanField()),
            ],
        ),
    ]
