# Generated by Django 5.2.1 on 2026-01-10 08:10

from django.db import migrations, models
from carbon_txt.web.validation_logging.models import ValidationLogEntry


class Migration(migrations.Migration):
    dependencies = [
        ("validation_logging", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="validationlogentry",
            name="source",
            field=models.CharField(
                choices=[
                    ("validator_api", "Validator Api"),
                    ("provider_portal", "Provider Portal"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="validationlogentry",
            name="endpoint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        # All existing logged entries occurred throught the validator api, so we
        # should label them as such:
        migrations.RunSQL(
            f"""
            UPDATE {ValidationLogEntry._meta.db_table}
            SET source='validator_api'
            """
        ),
    ]
