# Generated by Django 5.2.1 on 2026-01-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("validation_logging", "0002_validationlogentry_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="validationlogentry",
            name="endpoint",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
