# Generated by Django 5.2.1 on 2026-07-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('validation_logging', '0003_validationlogentry_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationlogentry',
            name='version',
            field=models.TextField(blank=True, null=True),
        ),
    ]
