version: 2

build:
  os: ubuntu-lts-latest
  tools:
      python: latest
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync  --frozen
    - uv run sphinx-build docs docs/_build/html
